name: Markdown to Presentation

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli

      - name: Convert Markdown to PDF
        run: |
          for file in $(find . -name "*.md"); do
            if grep -q "marp: true" "$file"; then
              output_file="${file%.md}.pdf"
              marp --pdf "$file" -o "$output_file"
              echo "Converted $file to $output_file"
            fi
          done

      - name: Upload PDFs
        uses: actions/upload-artifact@v2
        with:
          name: pdf-slides
          path: '**/*.pdf'
